import os
from typing import TypedDict, List

from langchain_core.documents import Document

from src.core.db import get_vector_store


# ── State ──────────────────────────────────────────────────────────────────────
# The state is the shared data that flows through the entire graph.
# Each node reads from state and returns updated state.
#
# New fields added for the NL2SQL (product) routing path:
#   route        — set by router_node: "product" | "document"
#   generated_sql — the SQL generated by the NL2SQL node
#   sql_result   — raw string output returned by executing the SQL

class RAGState(TypedDict):
    query: str
    retrieved_docs: List[Document]   # Output of Node 1 — wide retrieval (k=20)
    reranked_docs: List[Document]    # Output of Node 2 — narrowed by reranker (top_n=10)
    response: dict                   # Output of Node 3 — final structured answer
    route: str                       # "product" or "document" — set by router_node
    generated_sql: str               # SQL generated by nl2sql_node
    sql_result: str                  # Raw SQL execution result


# ── Node 1: Vector Search ──────────────────────────────────────────────────────
# Uses a bi-encoder (Google Gemini embeddings) to find semantically similar chunks.
# We retrieve k=20 to cast a wide net — the reranker will narrow this down to top 10.

def vector_search_node(state: RAGState) -> RAGState:
    vector_store = get_vector_store()
    docs = vector_store.similarity_search(state["query"], k=20)
    print(f"[vector_search_node] Retrieved {len(docs)} chunks from PGVector")
    return {**state, "retrieved_docs": docs}
